### ISSUE TITLE
Home assistant 0.80.3 showing 2 errors: Update for "sensor.toon_power_use" and  "sensor.toon_power_use_cnt" fails

### ISSUE THREAD

**Issue by kurniawan77** [cyberjunky/home-assistant-custom-components#11] opened 2018-10-24 19:30 UTC
**2018-10-24 20:48:24 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.toon_power_use fails**
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 349, in async_device_update
    await self.hass.async_add_job(self.update)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/sensor/toon_smartmeter.py", line 180, in update
    self._state = energy["dev_2.2"]["CurrentElectricityFlow"]
KeyError: 'CurrentElectricityFlow'

and

**2018-10-24 20:48:24 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.toon_power_use_cnt fails**
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 349, in async_device_update
    await self.hass.async_add_job(self.update)
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/sensor/toon_smartmeter.py", line 188, in update
    self._state = float(energy["dev_2.2"]["CurrentElectricityQuantity"])/1000
KeyError: 'CurrentElectricityQuantity'

**Comment by ualex73** [comment] 2018-10-27 12:20
Looking at the output of the request to the root'ed Toon, the 'dev_2.2' isn't a fixed type for a value, but it can be different - depending on the 'type' field. So the sensor needs to be reworked ...

My json output looks like:
{
  "dev_settings_device": {
    "uuid": "5a972349-3411-4f0d-af53-e5479b811b00",
    "name": "settings_device",
    "internalAddress": "settings_device",
    "type": "settings_device"
  },
  "dev_10": {
    "uuid": "835c006e-70a5-433e-9704-63611caa0f7d",
    "name": "HAE_METER_v2",
    "internalAddress": "10",
    "type": "HAE_METER_v2",
    "supportsCrc": "1",
    "ccList": "22 3c 3d 3e 56 60 70 72 7a 86 8b 73",
    "supportedCC": "22 3c 3d 3e 56 60 70 72 7a 86 8b 73",
    "nodeFlags": [],
    "IsConnected": "1",
    "HealthValue": "10",
    "DeviceName": ""
  },
  "dev_10.1": {
    "uuid": "98a51fc6-e693-4a1c-b41f-b078c836d809",
    "name": "HAE_METER_v2_1",
    "internalAddress": "10.1",
    "type": "gas",
    "supportsCrc": "0",
    "ccList": "3c 3d 3e 72 86",
    "supportedCC": "3c 3d 3e 72 86",
    "nodeFlags": [],
    "CurrentGasFlow": "6.00",
    "CurrentGasQuantity": "952857.00",
    "DeviceName": ""
  },
  "dev_10.2": {
    "uuid": "d7114605-ba09-474b-a290-22d6a2f0e21b",
    "name": "HAE_METER_v2_2",
    "internalAddress": "10.2",
    "type": "elec",
    "supportsCrc": "0",
    "ccList": "3c 3d 3e 72 86",
    "supportedCC": "3c 3d 3e 72 86",
    "nodeFlags": [],
    "CurrentElectricityFlow": "NaN",
    "CurrentElectricityQuantity": "NaN",
    "DeviceName": ""
  },
  "dev_10.3": {
    "uuid": "13dd0d4e-32b4-4942-8da8-4650e3e905e5",
    "name": "HAE_METER_v2_3",
    "internalAddress": "10.3",
    "type": "elec_delivered_nt",
    "supportsCrc": "0",
    "ccList": "3c 3d 3e 72 86",
    "supportedCC": "3c 3d 3e 72 86",
    "nodeFlags": [],
    "CurrentElectricityFlow": "0.00",
    "CurrentElectricityQuantity": "944917.00",
    "DeviceName": ""
  },
  "dev_10.4": {
    "uuid": "fd81469f-2e66-45a4-bef6-e3e39deefe18",
    "name": "HAE_METER_v2_4",
    "internalAddress": "10.4",
    "type": "elec_received_nt",
    "supportsCrc": "0",
    "ccList": "3c 3d 3e 72 86",
    "supportedCC": "3c 3d 3e 72 86",
    "nodeFlags": [],
    "CurrentElectricityFlow": "0.00",
    "CurrentElectricityQuantity": "0.00",
    "DeviceName": ""
  },
  "dev_10.5": {
    "uuid": "4d507239-6bb3-44ae-894c-39fe8e6faa93",
    "name": "HAE_METER_v2_5",
    "internalAddress": "10.5",
    "type": "elec_delivered_lt",
    "supportsCrc": "0",
    "ccList": "3c 3d 3e 72 86",
    "supportedCC": "3c 3d 3e 72 86",
    "nodeFlags": [],
    "CurrentElectricityFlow": "2172.00",
    "CurrentElectricityQuantity": "859815.00",
    "DeviceName": ""
  },
  "dev_10.6": {
    "uuid": "53d9b458-6a8e-4925-a40e-6973fa785cdc",
    "name": "HAE_METER_v2_6",
    "internalAddress": "10.6",
    "type": "elec_received_lt",
    "supportsCrc": "0",
    "ccList": "3c 3d 3e 72 86",
    "supportedCC": "3c 3d 3e 72 86",
    "nodeFlags": [],
    "CurrentElectricityFlow": "0.00",
    "CurrentElectricityQuantity": "0.00",
    "DeviceName": ""
  }
}

**Comment by RudolfRendier** [comment] 2018-11-05 19:32
Maybe a duplicate of https://github.com/cyberjunky/home-assistant-custom-components/issues/3?

**Comment by cyberjunky** [comment] 2019-01-12 09:25
If you un-pair the zwave energy sensor, and pair it with another or same Toon for example, the dev_x_x values can be even more different, I was thinking about making the fields configurable, but simple editing the component once is also sufficient.
I already inserted 3 known name conventions found:
```
    def update(self):
        """Get the latest data and use it to update our sensor state."""
        self.data.update()
        energy = self.data.data

        """Go to http://toon.ip:port/hdrv_zwave?action=getDevices.json and search for dev_"""
        if self.type == 'gasused':
            if 'dev_3.1' in energy:
                self._state = float(energy["dev_3.1"]["CurrentGasFlow"])/100
            elif 'dev_2.1' in energy:
                self._state = float(energy["dev_2.1"]["CurrentGasFlow"])/100
            elif 'dev_4.1' in energy:
                self._state = float(energy["dev_4.1"]["CurrentGasFlow"])/100
```
Etc

**Comment by ualex73** [comment] 2019-01-12 11:23
I created a pull request, which should fix the gas and delivered power - now it tries to detect the devid's, instead of fixed values :-)

**Comment by ualex73** [comment] 2019-01-20 15:51
Ok, I maybe can re-use the type, that's easier 👍

**Comment by HenkSnavel** [comment] 2019-02-21 09:34
I'm having the same error on hassio 87.1
This is my json output. What do I need to change in the python file? 

{
   "dev_4":{
      "uuid":"459bfad6-f13b-439c-a21d-84c2add5f059",
      "name":"Meetunit",
      "internalAddress":"4",
      "type":"HAE_METER_v3",
      "supportsCrc":"1",
      "ccList":"5e 86 72 32 56 5a 59 85 73 7a 60 8e 22 70 8b 3c 3d 3e",
      "supportedCC":"5e 86 72 32 56 5a 59 85 73 7a 60 8e 22 70 8b 3c 3d 3e",
      "nodeFlags":[

      ],
      "IsConnected":"1",
      "HealthValue":"10",
      "DeviceName":"Meetunit"
   },
   "dev_4.1":{
      "uuid":"c9b4bce9-354d-42ae-97c9-5a7c07dae3c0",
      "name":"HAE_METER_v3_1",
      "internalAddress":"4.1",
      "type":"HAE_METER_v3_1",
      "supportsCrc":"0",
      "ccList":"5e 59 85 8e 3c 3d 3e",
      "supportedCC":"5e 59 85 8e 3c 3d 3e",
      "nodeFlags":[

      ],
      "CurrentGasFlow":"0.00",
      "CurrentGasQuantity":"6135204.00",
      "DeviceName":""
   },
   "dev_4.2":{
      "uuid":"b4fe0227-2641-4fa6-a28e-a0350afb786f",
      "name":"HAE_METER_v3_2",
      "internalAddress":"4.2",
      "type":"HAE_METER_v3_2",
      "supportsCrc":"0",
      "ccList":"5e 59 85 8e 3c 3d 3e",
      "supportedCC":"5e 59 85 8e 3c 3d 3e",
      "nodeFlags":[

      ],
      "DeviceName":""
   },
   "dev_4.3":{
      "uuid":"2cb5d6f0-ebf7-4f46-9e9d-de262e2e4911",
      "name":"HAE_METER_v3_3",
      "internalAddress":"4.3",
      "type":"HAE_METER_v3_3",
      "supportsCrc":"0",
      "ccList":"5e 59 85 8e 3c 3d 3e",
      "supportedCC":"5e 59 85 8e 3c 3d 3e",
      "nodeFlags":[

      ],
      "DeviceName":"",
      "CurrentElectricityFlow":"NaN",
      "CurrentElectricityQuantity":"NaN"
   },
   "dev_4.4":{
      "uuid":"e24ca37e-abf1-4e41-96f8-374128a2b6f5",
      "name":"HAE_METER_v3_4",
      "internalAddress":"4.4",
      "type":"HAE_METER_v3_4",
      "supportsCrc":"0",
      "ccList":"5e 59 85 8e 3c 3d 3e",
      "supportedCC":"5e 59 85 8e 3c 3d 3e",
      "nodeFlags":[

      ],
      "DeviceName":"",
      "CurrentElectricityFlow":"100.00",
      "CurrentElectricityQuantity":"4317809.00"
   },
   "dev_4.5":{
      "uuid":"3ddf4297-1897-4a7f-84cf-fcf7527e6e2e",
      "name":"HAE_METER_v3_5",
      "internalAddress":"4.5",
      "type":"HAE_METER_v3_5",
      "supportsCrc":"0",
      "ccList":"5e 59 85 8e 3c 3d 3e",
      "supportedCC":"5e 59 85 8e 3c 3d 3e",
      "nodeFlags":[

      ],
      "DeviceName":"",
      "CurrentElectricityFlow":"0.00",
      "CurrentElectricityQuantity":"258.00"
   },
   "dev_4.6":{
      "uuid":"63cc7096-7af1-4114-b7bf-656741d277a9",
      "name":"HAE_METER_v3_6",
      "internalAddress":"4.6",
      "type":"HAE_METER_v3_6",
      "supportsCrc":"0",
      "ccList":"5e 59 85 8e 3c 3d 3e",
      "supportedCC":"5e 59 85 8e 3c 3d 3e",
      "nodeFlags":[

      ],
      "DeviceName":"",
      "CurrentElectricityFlow":"0.00",
      "CurrentElectricityQuantity":"3037369.00"
   },
   "dev_4.7":{
      "uuid":"1ff93e6e-1c49-44be-bb11-ddf0280fbe42",
      "name":"HAE_METER_v3_7",
      "internalAddress":"4.7",
      "type":"HAE_METER_v3_7",
      "supportsCrc":"0",
      "ccList":"5e 59 85 8e 3c 3d 3e",
      "supportedCC":"5e 59 85 8e 3c 3d 3e",
      "nodeFlags":[

      ],
      "DeviceName":"",
      "CurrentElectricityFlow":"0.00",
      "CurrentElectricityQuantity":"91.00"
   },
   "dev_4.8":{
      "uuid":"3f4c75bb-82e5-4466-a0e2-fd10b6e0ae6a",
      "name":"HAE_METER_v3_8",
      "internalAddress":"4.8",
      "type":"HAE_METER_v3_8",
      "supportsCrc":"0",
      "ccList":"5e 59 85 8e 3c 3d 3e",
      "supportedCC":"5e 59 85 8e 3c 3d 3e",
      "nodeFlags":[

      ],
      "DeviceName":"",
      "CurrentHeatQuantity":"NaN"
   }
}

**Comment by hiddit** [comment] 2019-03-18 08:40
with the most recent file's got this 

```
2019-03-18 09:31:46 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.toon_power_use_cnt fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 348, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/toon_smartmeter/sensor.py", line 210, in update
    self._state = float(energy["dev_2.2"]["CurrentElectricityQuantity"])/1000
KeyError: 'CurrentElectricityQuantity'
2019-03-18 09:31:46 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.toon_power_use fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 348, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/toon_smartmeter/sensor.py", line 202, in update
    self._state = energy["dev_2.2"]["CurrentElectricityFlow"]
KeyError: 'CurrentElectricityFlow'
```

**Comment by ualex73** [comment] 2019-03-18 08:48
@hiddit: can you copy-paste your json output?

**Comment by hiddit** [comment] 2019-03-18 08:56
@ualex73 uuh how do i get that?

**Comment by ualex73** [comment] 2019-03-18 08:59
Should be the following command, if you know the Toon's IP address:
curl http://toonip:10080/hdrv_zwave?action=getDevices.json

Search for 'dev_'

**Comment by hiddit** [comment] 2019-03-18 09:01
@ualex73 

`{"dev_2": {"uuid": "28d4f25c-ce24-4ad1-8932-beb02ac66129", "name": "HAE_METER_v3", "internalAddress": "2", "type": "HAE_METER_v3", "supportsCrc": "1", "ccList": "5e 86 72 32 56 5a 59 85 73 7a 60 8e 22 70 8b 3c 3d 3e", "supportedCC": "5e 86 72 32 56 5a 59 85 73 7a 60 8e 22 70 8b 3c 3d 3e", "nodeFlags": [], "IsConnected": "1", "HealthValue": "10", "DeviceName": "HAE_METER_v3"},`

`"dev_2.1": {"uuid": "a61279c2-0fc9-486e-834b-fb2e19a2a9ba", "name": "HAE_METER_v3_1", "internalAddress": "2.1", "type": "HAE_METER_v3_1", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "CurrentGasFlow": "104.00", "CurrentGasQuantity": "3905102.00", "DeviceName": "HAE_METER_v3_1"}, "dev_2.2": {"uuid": "8d17643d-dd65-40e1-85ee-3b79817521f7", "name": "HAE_METER_v3_2", "internalAddress": "2.2", "type": "HAE_METER_v3_2", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "DeviceName": "HAE_METER_v3_2"}, `

`"dev_2.3": {"uuid": "7959cda0-75be-4de9-b9c7-db7d98e2ff9b", "name": "HAE_METER_v3_3", "internalAddress": "2.3", "type": "HAE_METER_v3_3", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "DeviceName": "HAE_METER_v3_3", "CurrentElectricityFlow": "NaN", "CurrentElectricityQuantity": "NaN"},`

` "dev_2.4": {"uuid": "54bcb5fd-363f-49de-b7c7-176abdb34f43", "name": "HAE_METER_v3_4", "internalAddress": "2.4", "type": "HAE_METER_v3_4", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "DeviceName": "HAE_METER_v3_4", "CurrentElectricityFlow": "365.00", "CurrentElectricityQuantity": "4204126.00"},`

`"dev_2.5": {"uuid": "b482a368-4338-40e4-abce-18a60b9c212e", "name": "HAE_METER_v3_5", "internalAddress": "2.5", "type": "HAE_METER_v3_5", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "DeviceName": "HAE_METER_v3_5", "CurrentElectricityFlow": "0.00", "CurrentElectricityQuantity": "0.00"},`

` "dev_2.6": {"uuid": "22e37368-6b73-4e5d-a579-b6161c1141a6", "name": "HAE_METER_v3_6", "internalAddress": "2.6", "type": "HAE_METER_v3_6", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "DeviceName": "HAE_METER_v3_6", "CurrentElectricityFlow": "0.00", "CurrentElectricityQuantity": "3564692.00"},`

`"dev_2.7": {"uuid": "fb07991c-c626-40d0-b0fb-f1e04740916f", "name": "HAE_METER_v3_7", "internalAddress": "2.7", "type": "HAE_METER_v3_7", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "DeviceName": "HAE_METER_v3_7", "CurrentElectricityFlow": "0.00", "CurrentElectricityQuantity": "0.00"}, `

` "dev_2.8": {"uuid": "0ba029a2-d702-4259-a38c-12ca13265980", "name": "HAE_METER_v3_8", "internalAddress": "2.8", "type": "HAE_METER_v3_8", "supportsCrc": "0", "ccList": "5e 59 85 8e 3c 3d 3e", "supportedCC": "5e 59 85 8e 3c 3d 3e", "nodeFlags": [], "DeviceName": "HAE_METER_v3_8", "CurrentHeatQuantity": "NaN"},`

` "dev_settings_device": {"uuid": "ee5cd8f4-4143-4b29-946c-48f35aa3d489", "name": "settings_device", "internalAddress": "settings_device", "type": "settings_device"}}`

EDIT: i did split it up

**Comment by ualex73** [comment] 2019-03-18 09:17
Ok, I see the issue ... I think how to fix it, i will prepare a pull request tonight.

**Comment by ualex73** [comment] 2019-03-18 12:24
Ok, you can try the following file:
https://github.com/ualex73/home-assistant-custom-components/blob/master/toon_smartmeter/sensor.py

I should skip any missing variables ... Also you can remove the following items from 'resources':
      - elecusageflowpulse
      - elecusagecntpulse

**Comment by hiddit** [comment] 2019-03-18 17:03
got this now 

> Mon Mar 18 2019 17:53:50 GMT+0100 (Midden-Europese standaardtijd)
> Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/homeassistant/config_entries.py", line 559, in async_forward_entry_setup
>     self.hass, component, self._hass_config)
>   File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 45, in async_setup_component
>     return await setup_tasks[domain]  # type: ignore
>   File "/usr/local/lib/python3.7/site-packages/homeassistant/config_entries.py", line 559, in async_forward_entry_setup
>     self.hass, component, self._hass_config)
>   File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 45, in async_setup_component
>     return await setup_tasks[domain]  # type: ignore
>   File "/usr/local/lib/python3.7/site-packages/homeassistant/config_entries.py", line 559, in async_forward_entry_setup
>     self.hass, component, self._hass_config)
>   File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 45, in async_setup_component
>     return await setup_tasks[domain]  # type: ignore
>   File "/usr/local/lib/python3.7/site-packages/homeassistant/config_entries.py", line 559, in async_forward_entry_setup
>     self.hass, component, self._hass_config)
>   File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 45, in async_setup_component
>     return await setup_tasks[domain]  # type: ignore
>   File "/usr/local/lib/python3.7/site-packages/homeassistant/config_entries.py", line 559, in async_forward_entry_setup
>     self.hass, component, self._hass_config)
>   File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 45, in async_setup_component
>     return await setup_tasks[domain]  # type: ignore
>   File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 56, in async_setup_component
>     return await task  # type: ignore
>   File "/usr/local/lib/python3.7/site-packages/homeassistant/setup.py", line 124, in _async_setup_component
>     conf_util.async_process_component_config(hass, config, domain)
>   File "/usr/local/lib/python3.7/site-packages/homeassistant/config.py", line 743, in async_process_component_config
>     platform = get_platform(hass, domain, p_name)
>   File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 97, in get_platform
>     base_paths)
>   File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 166, in _load_file
>     module = importlib.import_module(path)
>   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 724, in exec_module
>   File "<frozen importlib._bootstrap_external>", line 860, in get_code
>   File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/config/custom_components/toon_smartmeter/sensor.py", line 171
>     if dev['type'] == 'HAE_METER_v2_2':
>                                       ^
> IndentationError: unindent does not match any outer indentation level

**Comment by ualex73** [comment] 2019-03-18 18:24
ok, latest revision should work ;-) So do again:

wget https://github.com/ualex73/home-assistant-custom-components/blob/master/toon_smartmeter/sensor.py

**Comment by hiddit** [comment] 2019-03-18 19:02
great got no errors back now, but only one sensor is working: Toon Power Use with unknown amount

**Comment by cyberjunky** [comment] 2019-12-25 14:17
Is this still an issue? I close, please re-open if needed.

**Closed as completed by cyberjunky** 2019-12-25 14:17 UTC

**Comment by Edwintenhaaf** [comment] 2023-03-08 10:48
Hello all,

Old thread but I have this issue for a while and cannot solve this myself.
the mentioned sensor doe not work for me.
Think that there should be some cleanup in the json. But is this safe ?
How to check what is the most recent ?

thanks, Edwin

my json output:
{
   "dev_settings_device":{
      "uuid":"9de67f9b-fc9b-4a0e-a16f-e80cd2294be4",
      "name":"settings_device",
      "internalAddress":"settings_device",
      "type":"settings_device"
   },
   "dev_3":{
      "uuid":"81daa8ba-bd8c-47fc-b82f-0e5e16a24810",
      "name":"Meterkast",
      "internalAddress":"3",
      "type":"HAE_METER_v3",
      "supportsCrc":"1",
      "ccList":"5e 86 72 32 56 5a 59 85 73 7a 60 8e 22 70 8b 3c 3d 3e",
      "supportedCC":"5e 86 72 32 56 5a 59 85 73 7a 60 8e 22 70 8b 3c 3d 3e",
      "nodeFlags":[
         
      ],
      "IsConnected":"1",
      "HealthValue":"10",
      "DeviceName":"Meterkast",
      "CurrentSensorStatus":"UNKNOWN"
   },
   "dev_3.1":{
      "uuid":"6ddf0bba-a001-49dc-bbb3-ac567d383f35",
      "name":"HAE_METER_v3_1",
      "internalAddress":"3.1",
      "type":"HAE_METER_v3_1",
      "supportsCrc":"0",
      "ccList":"5e 59 85 8e 3c 3d 3e",
      "supportedCC":"5e 59 85 8e 3c 3d 3e",
      "nodeFlags":[
         
      ],
      "CurrentSensorStatus":"OPERATIONAL",
      "CurrentGasFlow":"16.00",
      "CurrentGasQuantity":"4708181.00",
      "DeviceName":"HAE_METER_v3_1"
   },
   "dev_3.2":{
      "uuid":"3e17e7f8-ed27-4fe5-be41-460e839763ff",
      "name":"HAE_METER_v3_2",
      "internalAddress":"3.2",
      "type":"HAE_METER_v3_2",
      "supportsCrc":"0",
      "ccList":"5e 59 85 8e 3c 3d 3e",
      "supportedCC":"5e 59 85 8e 3c 3d 3e",
      "nodeFlags":[
         
      ],
      "CurrentSensorStatus":"UNKNOWN",
      "DeviceName":"HAE_METER_v3_2",
      "CurrentElectricityFlow":"NaN",
      "CurrentElectricityQuantity":"NaN"
   },
   "dev_3.3":{
      "uuid":"5f3262ed-6005-4525-a035-e9998d2b5459",
      "name":"HAE_METER_v3_3",
      "internalAddress":"3.3",
      "type":"HAE_METER_v3_3",
      "supportsCrc":"0",
      "ccList":"5e 59 85 8e 3c 3d 3e",
      "supportedCC":"5e 59 85 8e 3c 3d 3e",
      "nodeFlags":[
         
      ],
      "CurrentSensorStatus":"OPERATIONAL",
      "DeviceName":"HAE_METER_v3_3",
      "CurrentElectricityFlow":"638.00",
      "CurrentElectricityQuantity":"1406.00"
   },
   "dev_3.4":{
      "uuid":"0af4d535-50ee-4242-838f-c892e1372374",
      "name":"HAE_METER_v3_4",
      "internalAddress":"3.4",
      "type":"HAE_METER_v3_4",
      "supportsCrc":"0",
      "ccList":"5e 59 85 8e 3c 3d 3e",
      "supportedCC":"5e 59 85 8e 3c 3d 3e",
      "nodeFlags":[
         
      ],
      "CurrentSensorStatus":"OPERATIONAL",
      "DeviceName":"HAE_METER_v3_4",
      "CurrentElectricityFlow":"0.00",
      "CurrentElectricityQuantity":"18759175.00"
   },
   "dev_3.5":{
      "uuid":"d12bb828-02d9-479a-9891-534c6ff4241f",
      "name":"HAE_METER_v3_5",
      "internalAddress":"3.5",
      "type":"HAE_METER_v3_5",
      "supportsCrc":"0",
      "ccList":"5e 59 85 8e 3c 3d 3e",
      "supportedCC":"5e 59 85 8e 3c 3d 3e",
      "nodeFlags":[
         
      ],
      "CurrentSensorStatus":"UNKNOWN",
      "DeviceName":"HAE_METER_v3_5",
      "CurrentElectricityFlow":"189.00",
      "CurrentElectricityQuantity":"120.00"
   },
   "dev_3.6":{
      "uuid":"1bebd8e6-c540-4d1b-8290-d91e45dd5ecb",
      "name":"HAE_METER_v3_6",
      "internalAddress":"3.6",
      "type":"HAE_METER_v3_6",
      "supportsCrc":"0",
      "ccList":"5e 59 85 8e 3c 3d 3e",
      "supportedCC":"5e 59 85 8e 3c 3d 3e",
      "nodeFlags":[
         
      ],
      "CurrentSensorStatus":"UNKNOWN",
      "DeviceName":"HAE_METER_v3_6",
      "CurrentElectricityFlow":"0.00",
      "CurrentElectricityQuantity":"15870116.00"
   },
   "dev_3.7":{
      "uuid":"7c403ed9-960a-4a6b-bc1f-3338cc43c9ac",
      "name":"HAE_METER_v3_7",
      "internalAddress":"3.7",
      "type":"HAE_METER_v3_7",
      "supportsCrc":"0",
      "ccList":"5e 59 85 8e 3c 3d 3e",
      "supportedCC":"5e 59 85 8e 3c 3d 3e",
      "nodeFlags":[
         
      ],
      "CurrentSensorStatus":"UNKNOWN",
      "DeviceName":"HAE_METER_v3_7",
      "CurrentElectricityFlow":"0.00",
      "CurrentElectricityQuantity":"0.00"
   },
   "dev_3.8":{
      "uuid":"1089a64b-b6a5-48ee-9d58-6bfeac555969",
      "name":"HAE_METER_v3_8",
      "internalAddress":"3.8",
      "type":"HAE_METER_v3_8",
      "supportsCrc":"0",
      "ccList":"5e 59 85 8e 3c 3d 3e",
      "supportedCC":"5e 59 85 8e 3c 3d 3e",
      "nodeFlags":[
         
      ],
      "CurrentSensorStatus":"UNKNOWN",
      "DeviceName":"HAE_METER_v3_8",
      "CurrentHeatQuantity":"NaN",
      "CurrentHeatFlow":"NaN"
   }
}
